// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace QTS.Excesion
{
    internal sealed partial class Vsix
    {
        public const string Id = "QTSExcesion.8a1e960e-23d2-44dc-83a6-d72ce62987f5";
        public const string Name = "QTSExcesion";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "zh-Hans";
        public const string Version = "1.0";
        public const string Author = "Sigeer";
        public const string Tags = "";
    }
}
