// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace QTS.Excesion
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string QTSExcesionString = "133904a6-d275-4c8a-8c78-5f0be8e10032";
        public static Guid QTSExcesion = new Guid(QTSExcesionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TopMeun = 0x0010;
        public const int TopMeunGroup = 0x0011;
        public const int Toolbar = 0x0015;
        public const int ToolbarGroup = 0x0016;
        public const int RightGroup = 0x0020;
        public const int PublishButton = 0x0102;
        public const int PackButton = 0x0103;
        public const int SetButton = 0x0104;
    }
}